apiVersion: batch/v1
kind: Job
metadata:
  name: cmsrun-job
spec:
  template:
    spec:
      containers:
      - name: cmsrun-job
        image: geddes-registry.rcac.purdue.edu/cms/sonic-client-cms-miniaod:cmssw_16
        command: ["/entrypoint.sh"]
        args:
          - "--address=sonic-server.cms.geddes.rcac.purdue.edu"
          - "--port=8001"
        env:
          - name: X509_USER_PROXY
            value: /etc/grid-security-ro/x509up
        volumeMounts:
          - name: cvmfs
            mountPath: /cvmfs
            mountPropagation: HostToContainer
          - name: x509-proxy
            mountPath: /etc/grid-security-ro
            readOnly: true
        resources:
          requests:
            memory: "32Gi"
            cpu: "8"
          limits:
            memory: "32Gi"
            cpu: "8"
      restartPolicy: Never
      volumes:
        - name: cvmfs
          persistentVolumeClaim:
            claimName: cvmfs
        - name: x509-proxy
          secret:
            secretName: af-x509-proxy
            defaultMode: 384  # 0600 - required by grid tools (no group/other read)
      nodeSelector:
        cms-af-prod: 'true'
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"

  backoffLimit: 0
