apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build-job-sonic
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args:
          - "--context=git://github.com/kondratyevd/sonic-client-cms-miniaod.git"
          - "--context-sub-path=docker/"
          - "--dockerfile=Dockerfile"
          - "--destination=geddes-registry.rcac.purdue.edu/cms/sonic-client-cms-miniaod:latest"
          - "--cache=true"
          # - "--no-push"
        resources:
          requests:
            memory: "32Gi"
            cpu: "8"
          limits:
            memory: "32Gi"
            cpu: "8"
        volumeMounts:
          - name: docker-config
            mountPath: /kaniko/.docker/
          - name: cvmfs
            mountPath: /cvmfs
            mountPropagation: HostToContainer
      restartPolicy: Never
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
        - name: cvmfs
          persistentVolumeClaim:
            claimName: cvmfs
      nodeSelector:
        cms-af-prod: 'true'
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"
