apiVersion: batch/v1
kind: Job
metadata:
  name: cmsrun-job
spec:
  template:
    spec:
      containers:
      - name: cmsrun-job
        image: geddes-registry.rcac.purdue.edu/cms/sonic-client-cms-miniaod:latest
        command: ["/entrypoint.sh"]
        args:
          - "--address=sonic-test-server.cms.geddes.rcac.purdue.edu"
          - "--port=8001"
        volumeMounts:
          - name: cvmfs
            mountPath: /cvmfs
            mountPropagation: HostToContainer
        resources:
          requests:
            memory: "32Gi"
            cpu: "8"
          limits:
            memory: "32Gi"
            cpu: "8"
      restartPolicy: Never
      volumes:
        - name: cvmfs
          hostPath: 
            path: /cvmfs
      nodeSelector:
        cms-af-prod: 'true'
      tolerations:
        - key: "hub.jupyter.org/dedicated"
          operator: "Equal"
          value: "cms-af"
          effect: "NoSchedule"

  backoffLimit: 0
